[project]
name = "stacks-clicker-v2i"
description = "Transaction Generator App v2i - Click to generate Stacks transactions!"
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.clicker-v2i]
path = "contracts/clicker-v2i.clar"

[contracts.tipjar-v2i]
path = "contracts/tipjar-v2i.clar"

[contracts.quickpoll-v2i]
path = "contracts/quickpoll-v2i.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
